=== Makar557/FourthTermFiles/СТПвInternet/Лабы/Java_3_4/files/xmlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="collection" type="EmployeeCollection"/>
    <xs:complexType name="EmployeeCollection">
        <xs:sequence>
            <xs:element type="Employee" name="employee" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Employee">
        <xs:sequence>
            <xs:element name="name"     type="xs:string"/>
            <xs:element name="age"      type="xs:integer"/>
            <xs:element name="salary"   type="xs:float"/>
            <xs:any minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="qualification">
        <xs:restriction base="xs:string">
            <xs:enumeration value="junior"/>
            <xs:enumeration value="middle"/>
            <xs:enumeration value="senior"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Makar557/FourthTermFiles/СТПвInternet/Лабы/Java_3_4/files/xmlFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="xmlSchema.xsd">
    <employee>
        <name>Petya</name>
        <age>25</age>
        <salary>700</salary>
        <qualification>middle</qualification>
    </employee>

    <employee>
        <name>Vasya</name>
        <age>19</age>
        <salary>850</salary>
    </employee>

    <employee>
        <name>Vanya</name>
        <age>32</age>
        <salary>1300</salary>
    </employee>

    <employee>
        <name>Max</name>
        <age>23</age>
        <salary>600</salary>
        <qualification>junior</qualification>
    </employee>
</collection>
